"""Build the versionable analysis tables and fixed indices for Slice 2."""

from __future__ import annotations

import json
from pathlib import Path
import sys


STUDY_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(STUDY_DIR))

from src.constants import MODELING_OUTPUT_NAMES
from src.data import load_dataset, validate_dataset
from src.output_analysis import (
    audit_output_transformations,
    high_correlation_pairs,
    input_output_sensitivity,
    output_correlations,
    ranked_sensitivities,
    summarize_outputs,
)
from src.splitting import SPLIT_FRACTIONS, SPLIT_SEEDS, make_regression_splits


ARTIFACT_DIR = STUDY_DIR / "artifacts" / "slice2"


def _format_pairs(records: list[dict[str, object]]) -> str:
    if not records:
        return "None at the configured threshold."
    return ", ".join(
        f"{record['output_1']}–{record['output_2']} "
        f"({float(record['correlation']):.3f})"
        for record in records
    )


def build_artifacts() -> None:
    """Regenerate all Slice 2 outputs deterministically."""
    ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)
    manifest: dict[str, object] = {
        "split_fractions": dict(zip(("train", "validation", "test"), SPLIT_FRACTIONS)),
        "stratification_output": "Fuel_Swelling",
        "stratification_bins": 10,
        "transformation_diagnostic": {
            "formula": "log1p(y / median_positive_supplied_y)",
            "note": (
                "Descriptive statistics only; no transformation is selected. "
                "Any later modeling scale must be fitted on training data only."
            ),
        },
        "datasets": {},
    }
    report_sections = [
        "# Slice 2 findings",
        "",
        "These artifacts were generated by `scripts/build_slice2_artifacts.py`.",
        "All correlations and summaries are exploratory; the fixed splits are "
        "the partitions to use for later surrogate comparisons.",
        "Output selection is undecided and awaits review. All available modeling "
        "outputs are included; Porosity is excluded per the study instructions.",
    ]

    for dataset in ("RERTR5", "RERTR12"):
        frame = load_dataset(dataset)
        validate_dataset(dataset, frame)
        summary = summarize_outputs(dataset, frame)
        correlations = output_correlations(dataset, frame)
        transformations = audit_output_transformations(dataset, frame)
        sensitivity = input_output_sensitivity(dataset, frame)
        ranking = ranked_sensitivities(sensitivity)
        high_pearson = high_correlation_pairs(correlations["pearson"])
        high_spearman = high_correlation_pairs(correlations["spearman"])
        splits = make_regression_splits(
            frame["Fuel_Swelling"], seed=SPLIT_SEEDS[dataset]
        )

        summary.to_csv(ARTIFACT_DIR / f"{dataset}_output_summary.csv")
        correlations["pearson"].to_csv(
            ARTIFACT_DIR / f"{dataset}_output_pearson.csv"
        )
        correlations["spearman"].to_csv(
            ARTIFACT_DIR / f"{dataset}_output_spearman.csv"
        )
        transformations.to_csv(
            ARTIFACT_DIR / f"{dataset}_transformations.csv"
        )
        sensitivity.to_csv(
            ARTIFACT_DIR / f"{dataset}_input_output_spearman.csv"
        )
        ranking.to_csv(
            ARTIFACT_DIR / f"{dataset}_sensitivity_ranking.csv"
        )
        splits.to_csv(ARTIFACT_DIR / f"{dataset}_split_indices.csv", index=False)

        split_counts = splits["split"].value_counts()
        manifest["datasets"][dataset] = {
            "rows": len(frame),
            "modeling_outputs": list(MODELING_OUTPUT_NAMES[dataset]),
            "high_pearson_pairs_absolute_ge_0.85": high_pearson.to_dict("records"),
            "high_spearman_pairs_absolute_ge_0.85": high_spearman.to_dict("records"),
            "split_seed": SPLIT_SEEDS[dataset],
            "split_counts": {
                name: int(split_counts[name])
                for name in ("train", "validation", "test")
            },
        }

        report_sections.extend(
            [
                "",
                f"## {dataset}",
                "",
                "High absolute Spearman pairs (≥ 0.85): "
                + _format_pairs(high_spearman.to_dict("records")),
                "",
                "Transformation tables report raw and scale-aware log1p "
                "skewness for all modeling outputs; no transformation is selected.",
                "",
                "Split: 2,240 training, 480 validation, and 480 test rows, "
                "stratified over ten Fuel_Swelling rank bins.",
            ]
        )

    (ARTIFACT_DIR / "manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8"
    )
    (ARTIFACT_DIR / "README.md").write_text(
        "\n".join(report_sections) + "\n", encoding="utf-8"
    )


if __name__ == "__main__":
    build_artifacts()
